#!/usr/bin/env python

__author__ = "Christopher and Cody Reichert"
__copyright__ = "Copyright 2015, SimplyRETS Inc. <support@simplyrets.com>"
__credits__ = ["Christopher Reichert", "Cody Reichert"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Christopher Reichert"
__email__ = "christopher@simplyrets.com"
__status__ = "Production"

class Agent:
    """ NOTE: This class is auto generated by the SimplyRets code
              generator program.  Do not edit the class manually.
    """

    def __init__(self):
        self.simplyRetsTypes = {
            'lastName': 'str',
            'contact': 'ContactInformation',
            'firstName': 'str',
            'id': 'str'

        }

        # Agent last name
        self.lastName = None # str
        # Agent contact info. This information is only present when your RETS feed specifies the agent wishes to show their contact information publicly.
        self.contact = None # ContactInformation
        # Agent first name
        self.firstName = None # str
        # Well known Agent MLS number or id.
        self.id = None # str
