#!/usr/bin/env python

__author__ = "Christopher and Cody Reichert"
__copyright__ = "Copyright 2015, SimplyRETS Inc. <support@simplyrets.com>"
__credits__ = ["Christopher Reichert", "Cody Reichert"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Christopher Reichert"
__email__ = "christopher@simplyrets.com"
__status__ = "Production"

class ContactInformation:
    """ NOTE: This class is auto generated by the SimplyRets code
              generator program.  Do not edit the class manually.
    """

    def __init__(self):
        self.simplyRetsTypes = {
            'office': 'byte',
            'cell': 'str',
            'full': 'str'
        }

        # Contact Information Office Phone Number
        self.office = None # byte
        # Contact Information Cell Phone
        self.cell = None # str
        # Full pretty-printed address with suffix (if available)
        self.full = None # str
