#!/usr/bin/env python

__author__ = "Christopher and Cody Reichert"
__copyright__ = "Copyright 2015, SimplyRETS Inc. <support@simplyrets.com>"
__credits__ = ["Christopher Reichert", "Cody Reichert"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Christopher Reichert"
__email__ = "christopher@simplyrets.com"
__status__ = "Production"

class GeographicData:
    """ NOTE: This class is auto generated by the SimplyRets code
              generator program.  Do not edit the class manually.
    """

    def __init__(self):
        self.simplyRetsTypes = {
            'county': 'str',
            'lat': 'float',
            'lng': 'float',
            'marketArea': 'str',
            'directions': 'str'

        }

        # Listing county
        self.county = None # str
        # Listing latitude (if available)
        self.lat = None # float
        # Listing longitude (if available)
        self.lng = None # float
        # Listing GeoMarket area. May be the same as mlsArea
        self.marketArea = None # str
        # Directions to the property
        self.directions = None # str
