#!/usr/bin/env python

__author__ = "Christopher and Cody Reichert"
__copyright__ = "Copyright 2015, SimplyRETS Inc. <support@simplyrets.com>"
__credits__ = ["Christopher Reichert", "Cody Reichert"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Christopher Reichert"
__email__ = "christopher@simplyrets.com"
__status__ = "Production"

class MlsInformation:
    """ NOTE: This class is auto generated by the SimplyRets code
              generator program.  Do not edit the class manually.
    """

    def __init__(self):
        self.simplyRetsTypes = {
            'status': 'str',
            'area': 'str',
            'daysOnMarket': 'long'
        }

        # MLS Status Code. Compliant with data dictionary v1.3 ListingStatus
        self.status = None # str
        # MLS Area. Generally a subdivision or community name.
        self.area = None # str
        # Amount of days the property has been Active
        self.daysOnMarket = None # long
