#!/usr/bin/env python

__author__ = "Christopher and Cody Reichert"
__copyright__ = "Copyright 2015, SimplyRETS Inc. <support@simplyrets.com>"
__credits__ = ["Christopher Reichert", "Cody Reichert"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Christopher Reichert"
__email__ = "christopher@simplyrets.com"
__status__ = "Production"

class Office:
    """ NOTE: This class is auto generated by the SimplyRets code
              generator program.  Do not edit the class manually.
    """
    def __init__(self):
        self.simplyRetsTypes = {
            'contact': 'ContactInformation',
            'name': 'str',
            'servingName': 'str',
            'brokerid': 'str'
        }

        self.contact = None # ContactInformation
        self.name = None # str
        self.servingName = None # str
        self.brokerid = None # str
