#!/usr/bin/env python

__author__ = "Christopher and Cody Reichert"
__copyright__ = "Copyright 2015, SimplyRETS Inc. <support@simplyrets.com>"
__credits__ = ["Christopher Reichert", "Cody Reichert"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Christopher Reichert"
__email__ = "christopher@simplyrets.com"
__status__ = "Production"

class StreetAddress:
    """ NOTE: This class is auto generated by the SimplyRets code
              generator program.  Do not edit the class manually.
    """

    def __init__(self):
        self.simplyRetsTypes = {
            'country': 'str',
            'postalCode': 'str',
            'streetName': 'str',
            'city': 'str',
            'streetNumber': 'long',
            'full': 'str'

        }

        # Street address country (United States or Canada)
        self.country = None # str
        # Street Address postal code
        self.postalCode = None # str
        # Name of the street
        self.streetName = None # str
        # City name
        self.city = None # str
        # Street number
        self.streetNumber = None # long
        # Full pretty-printed address with suffix (if available)
        self.full = None # str
